TITLE[0]="No instrumentation"
TITLE[1]="Null handlers"
TITLE[2]="Identity Handler"
TITLE[3]="Buffered Identity Handler with binary encoding"
TITLE[4]="Buffered Identity Handler with ZSTD compression"
TITLE[5]="Buffered Identity Handler with LZO1X compression"
