name: Benchmark Kieker-java Ubuntu 22.04
on:
  workflow_dispatch:
  push:
    branches: [ main, ubuntu2204 ]
  schedule: 
    - cron: "0 3 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Performance measurement
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Set up JDK ${{ matrix.java }}
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: 3.8.8
          java-distribution: 'temurin'
          java-version: 21
      - name: Execute MooBench Benchmark
        run: |
          ./setup.sh
          cd frameworks/Kieker-java/
          export NUM_OF_LOOPS=10 
          export MOOBENCH_CONFIGURATIONS="6"
          ./benchmark.sh 
          cd results-Kieker-java
          unzip results.zip 
          ../../../analysis/getGHActionsFormat.sh &> output.json
          cat output.json
          mv output.json ../../../
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Kieker-java'
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
      - name: Analyze benchmark results with Nyrkiö
        uses: nyrkio/change-detection@v2
        with:
          name: 'Kieker-java'
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nyrkio-token: ${{ secrets.NYRKIO_JWT_TOKEN }}
          auto-push: true
