name: Benchmark Kieker-java
on:
  workflow_dispatch:
  push:
    branches: [ main, continuous-gh-benchmarks, daily ]
  schedule: 
    - cron: "0 3 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - sustain1
    name: Performance measurement
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.5.3'
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Execute MooBench Benchmark
        run: |
          ./setup.sh
          cd frameworks/Kieker-java/
          export NUM_OF_LOOPS=10 
          export MOOBENCH_CONFIGURATIONS="0 1 2 4"
          ./benchmark.sh 
          cd results-Kieker-java
          unzip results.zip 
          ../../../analysis/getGHActionsFormat.sh &> output.json
          cat output.json
          mv output.json ../../../
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Kieker-java'
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
      - name: Analyze benchmark results with Nyrkiö
        uses: nyrkio/change-detection@HEAD
        with:
          name: 'Kieker-java'
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nyrkio-token: ${{ secrets.NYRKIO_JWT_TOKEN }}
          auto-push: true
